# -*- coding: utf-8 -*-
"""data_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1moNAO0Sh27enPU9IBHtmuATDwURHQT46

# Génération du dataset pour le projet
"""

import numpy as np
import random
import pandas as pd
import os

# Définir les listes de prénoms et de noms
prenoms = np.array(['Alice', 'Ali', 'Charlie', 'Diana', 'Eva', 'Frank'])
noms = np.array(['Kouakou', 'Bamba', 'Koffi', 'Yao', 'Ouattara', 'Oulaï'])

# 2. Définir le nombre d'identités à générer
taille = 50

# 3. Générer des combinaisons aléatoires
prenoms_aleatoires = np.random.choice(prenoms, size=taille)
noms_aleatoires = np.random.choice(noms, size=taille)

# 4. Concaténer pour obtenir des noms complets
prenom = np.char.add(prenoms_aleatoires, ' ')
name = np.char.add(prenom, noms_aleatoires)

print(name)

# Générer 50 âges entre 15 et 70 ans inclus
ages = np.random.randint(15, 70, 50)
print(ages)

liste_interests =[
  "technology",
  "fitness",
  "music",
  "sports",
  "travel",
  "photography",
  "gaming",
  "cooking",
  "fashion",
  "finance",
  "business",
  "entrepreneurship",
  "art",
  "movies",
  "books",
  "science",
  "health",
  "education",
  "automotive",
  "real_estate",
  "cryptocurrency",
  "artificial_intelligence",
  "sustainability",
  "gardening",
  "pets"
]

interests= []

for i in range(50):

    nb_interests = random.randint(1, 5)

    liste_interests_aleatoire = random.sample(liste_interests, nb_interests)

    interests.append(liste_interests_aleatoire)
interests

liste_activity_log = [
    "viewed_page",
    "viewed_product",
    "viewed_video",
    "viewed_article",
    "searched_query",
    "searched_product",
    "searched_ai_tools",
    "liked_post",
    "liked_video",
    "liked_comment",
    "shared_post",
    "shared_video",
    "commented_post",
    "saved_post",
    "followed_user",
    "watched_video",
    "watched_ai_talk",
    "watched_webinar",
    "watched_tutorial",
    "watched_movie",
    "listened_to_music",
    "listened_to_rock_music",
    "listened_to_podcast",
    "liked_song",
    "followed_artist",
    "added_to_cart",
    "removed_from_cart",
    "added_to_wishlist",
    "started_checkout",
    "completed_purchase",
    "bought_headphones",
    "bought_laptop",
    "bought_book",
    "reviewed_product",
    "rated_product",
    "installed_app",
    "opened_app",
    "upgraded_subscription",
    "renewed_subscription",
    "signed_up",
    "logged_in",
    "updated_profile",
    "sent_message",
    "joined_group",
    "downloaded_file",
    "uploaded_file",
    "completed_course",
    "attended_ai_talk",
    "booked_hotel",
    "booked_flight",
    "visited_restaurant",
    "attended_event",
    "played_game",
    "earned_achievement",
    "bought_stock",
    "sold_stock",
    "started_workout",
    "completed_workout",
    "tracked_steps"
    "liked a post",
    "viewed a video",
    "watched AI talk",
    "listened to rock music",
    "listened to a podcast",
    "searched for headphones",
    "viewed a product",
    "added headphones to cart",
    "bought headphones",
    "reviewed headphones",
    "followed an artist",
    "shared a video",
    "commented on a post",
    "completed a course",
    "attended an AI conference",
    "booked a hotel",
    "played a game",
    "completed a workout"
]

activity_log= []

for i in range(50):

    nb_activity_log = random.randint(1,3)

    activity_log_aleatoire = random.sample(liste_activity_log, nb_activity_log)

    activity_log.append(activity_log_aleatoire)

activity_log

# Création du DataFrame Pandas
data = pd.DataFrame(list(zip(name, ages, interests, activity_log)), columns=["Name", "Age", "Interests", "Activity Logs)"])

# Affichage du résultat
data.head(10)

os.makedirs('data', exist_ok=True)
data.to_json('data/users_raw.json', orient='records', indent=4)
print("Fichier users_raw.json enregistré avec succès danss le dossier /data ")