# -*- coding: utf-8 -*-
"""data_processor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UmZPB0XHxqv8G9zC7NRhf4vtd6L2QMid
"""

# importation des bibliothèques
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data = pd.read_json("/data/users_raw.json")
data.head()

"""#### Infos générales du Dataset"""

print(f"Shape du dataframe: {data.shape}")
print(f"\nTypes de données:\n{data.dtypes}")
print(f"\nInformations générales:\n")
print(data.info())
print("\n")
print(data.describe())
print("\n")
# identification des lignes en doublons
doublons_count = data.astype(str).duplicated().sum()
print(f"Nombre de lignes en double dans le dataset : {doublons_count}\n")
# identification des valeurs manquantes
print(f"Valeurs manquantes par colonne:\n{data.isnull().sum()}\n")
print(f"Pourcentage de valeurs manquantes:\n{data.isnull().sum() / len(data) * 100}\n")
print("\n")

"""### Nettoyage des données"""

# Suppression des doublons (astype(str) pour identifier les doublons malgré les listes)
data = data[~data.astype(str).duplicated()].reset_index(drop=True)
print(f"Doublons supprimés. Nouvelle taille du dataset : {data.shape}")

# Détection des valeurs aberrantes dans l'âge
print(f"Statistiques descriptives:\n{data['Age'].describe()}\n")
print(f"Valeurs uniques d'âge:\n{sorted(data['Age'].unique())}\n")
# Détection des outliers avec IQR
Q1 = data['Age'].quantile(0.25)
Q3 = data['Age'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
print(f"\nBornes IQR pour l'âge: [{lower_bound}, {upper_bound}]\n")
age_outliers = data[(data['Age'] < lower_bound) | (data['Age'] > upper_bound)]
print(f"Âges aberrants (outliers IQR):\n{age_outliers[['Name', 'Age']]}")

plt.figure(figsize=(10, 6))
sns.boxplot(x=data['Age'])
plt.title("Distribution de l'Âge (Boxplot) Avant ")
plt.xlabel("Âge")
plt.show()

# traitement des valeurs manquantes , des outliers (valeurs aberantes)

# Nettoyage colonne Age
data.loc[
    (data["Age"] < 14) |
    (data["Age"] > 100),
    "Age"] = np.nan
print(f"Valeurs manquantes dans 'Age' : {data['Age'].isnull().sum()}")

data['Age'] = data['Age'].fillna(data['Age'].median())
print("Valeurs manquantes dans 'Age' remplacées par la médiane.")
print(f"Nombre de valeurs nulles restantes : {data['Age'].isnull().sum()}")

# Nettoyage colonne interests
def clean_interests(interests):
    return [i for i in interests if i is not None]

data['Interests'] = data['Interests'].apply(clean_interests)

from scipy import stats
import numpy as np


interests_str = data['Interests'].apply(lambda x: str(x) if isinstance(x, list) and len(x) > 0 else np.nan)


mode_val = interests_str.mode()[0]


mode_list = data['Interests'][interests_str == mode_val].iloc[0]


data['Interests'] = data['Interests'].apply(lambda x: mode_list if (not isinstance(x, list) or len(x) == 0) else x)

print(f"Mode utilisé pour l'imputation : {mode_list}")
print(f"Nombre de listes vides restantes : {data['Interests'].apply(lambda x: len(x) == 0).sum()}")

data.head(50)

plt.figure(figsize=(10, 6))
sns.boxplot(x=data['Age'])
plt.title("Distribution de l'Âge (Boxplot) Apres")
plt.xlabel("Âge")
plt.show()

# Exportation du DataFrame au format CSV
path = 'data/users_clean.csv'
data.to_csv(path)

print(f"Le fichier users_clean.csv a été généré avec succès.")