# -*- coding: utf-8 -*-
"""generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rFbT5ItiEXER74AoXsZ0v82w9JzRMTX0
"""

import pandas as pd

data = pd.read_json("/content/users_raw.json")
data.head()

"""#### Analyse Exploratoire des Données (EDA)"""

print("Dataset Shape:", data.shape)
print("\nNom des colonnes:")
print(data.columns.tolist())

data.info()

"""#### Préparation et Nettoyage des Données"""

data_print = data.copy()
data_print['Interests'] = data_print['Interests'].apply(tuple)
data_print['Activity Logs)'] = data_print['Activity Logs)'].apply(tuple)
print("les lignes en doublons:", data_print.duplicated().sum())

# Exportation du DataFrame au format JSON
data.to_csv('users_clean.csv')

print("Le fichier 'users_clean.csv' a été généré avec succès.")