# -*- coding: utf-8 -*-
"""stats_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16aCqF8wNQ6rMXhUNwIvx8iwH8LgrH50-
"""

# importation des bibliothèques
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

#df = pd.read_csv("/data/users_clean.csv")
#df.head()

df = pd.read_csv("/content/users_clean.csv")
df # a supprimer

clean_interests_str = df['Interests'].astype(str).str.strip("[]").str.replace("'", "")
list_of_interests = clean_interests_str.str.split(", ")
all_interests_list = [item.strip() for sublist in list_of_interests for item in sublist if item and item != 'nan']

clean_activities_str = df['Activity Logs'].astype(str).str.strip("[]").str.replace("'", "")
list_of_activities = clean_activities_str.str.split(", ")
all_activities_list = [item.strip() for sublist in list_of_activities for item in sublist if item and item != 'nan']

# Affichage des résultats
print(f"Nombre d'intérêts : {len(all_interests_list)}")
print(f"Aperçu intérêts : {all_interests_list[:5]}")
print(f"\nNombre d'activités : {len(all_activities_list)}")
print(f"Aperçu activités : {all_activities_list[:5]}")

def get_top_10(data_list):
    counts = {}
    for item in data_list:
        counts[item] = counts.get(item, 0) + 1

    sorted_items = sorted(counts.items(), key=lambda x: x[1], reverse=True)
    return sorted_items[:10]

top_10_interests = get_top_10(all_interests_list)
top_10_activities = get_top_10(all_activities_list)

print("TOP 10 INTÉRÊTS :")
for item, count in top_10_interests:
    print(f"{item:40} {count}")

print("\nTOP 10 ACTIVITÉS :")
for item, count in top_10_activities:
    print(f"{item:40} {count}")

# 1. Analyse descriptive
print("ANALYSE DESCRIPTIVE\n")

print(f"Total Users: {len(df)}")
print(f"Age Range: {df['Age'].min()} - {df['Age'].max()} years")
print(f"Average Age: {df['Age'].mean():.1f} years")
print(f"Median Age: {df['Age'].median():.1f} years")

# Age distribution
age_groups = pd.cut(df['Age'], bins=[0, 25, 35, 50, 100], labels=['15-25', '26-35', '36-50', '51+'])
print(f"\nAge Distribution:")
print(age_groups.value_counts())

# Graphique de la distribution
plt.figure(figsize=(8, 6))
sns.countplot(x=age_groups)
plt.xlabel('Age par groupe')
plt.ylabel('Nombre de Users')
plt.title('Distribution de Users par Age de groupe')
plt.show()

# graphique des Activités Log
plt.figure(figsize=(10, 6))
sns.barplot(x=[activity for activity, _ in top_10_activities], y=[count for _, count in top_10_activities])
plt.xlabel('Activity Log')
plt.ylabel('Count')
plt.title('Top 10 Activity Log')
plt.xticks(rotation=45)
plt.show()

top_int_name, top_int_count = top_10_interests[0]
top_act_name, top_act_count = top_10_activities[0]


pct_interest = (top_int_count / len(df)) * 100
pct_activity = (top_act_count / len(df)) * 100

print(f" {top_int_name} apparaît chez {top_int_count} personnes à ({pct_interest:.1f}%) C'est l'intérêt le plus populaire")
print(f" {top_act_name} apparaît chez {top_act_count} personnes à ({pct_activity:.1f}%) C'est l'activité log la plus effectuée")

from scipy import stats

# ANALYSE STATISTIQUE AVEC SCIPY

# test Chi 2
print("\n TEST CHI 2 - Interest Distribution \n")

# Correction du nom de la variable : top_10_interests au lieu de top_interests
print(f"Top 5 interests: {dict(top_10_interests[:5])}")
observed_freq = np.array([count for interest, count in top_10_interests[:5]])
expected_freq = np.array([sum(observed_freq)/5] * 5)
chi2_stat, p_value = stats.chisquare(observed_freq, expected_freq)

print(f"Vérifions si le Top 5 des centres d'intérêt sont répartis de manière égale :")
print(f"Fréquences observées: {observed_freq}")
print(f"Fréquences Espérées: {expected_freq}")
print(f"Chi carré : {chi2_stat:.2f}")
print(f"P-value: {p_value:.4f} \n")

if p_value < 0.05:
    print(f"Résultat : Différence significative (p < 0,05) - Les centres d'intérêt ne sont PAS répartis de manière uniforme")
    print(f"{top_int_name} est vraiment populaire")
else:
    print(f"Résultat : Pas de différence significative (p > 0,05) - Les centres d'intérêt sont répartis de manière uniforme (Peut-être dû au hasard)")